### ISSUE TITLE
Tag docker image with specific version

### ISSUE THREAD

**Issue by DerkSchooltink** [codekie/openapi-examples-validator#134]
Right now the image is always tagged latest. Older image versions have to be referenced by the digest (ie `8df02b01e325be8ac247ae12dfef405bc5de51e2e49a72cc61b3856ec2d53a10` for version 4.3.2) which is inconvenient because you have to go to the docker hub to find out which version you are running.

Ideally the Docker image would be tagged with the same version as the version of the release on Github and NPMJS.

This is by no means an urgent issue, but a nice to have nonetheless. 😄

**Comment by codekie** [comment]
Yes, I know. When I set up docker for it, I also have set up an automated build-job on docker-hub that's supposed to automatically build and tag a new version, whenever a new version is tagged in GitHub. But for some weird reason the job did not work, even though the regex for the version is correct. I gave up at some point and decided to deal with it later. Maybe you have an idea why it isn't working? 😉 

![Bildschirmfoto 2021-02-15 um 13 31 46](https://user-images.githubusercontent.com/1512840/107947737-1948a900-6f93-11eb-8351-738479e0887c.png)

None of the rules work, even though all of them are based on the provided examples on docker-hub (the rule for `version-{\1}` even is an exact copy of one of the provided examples)

**Comment by codekie** [comment]
This is handled by GitHub actions now.

From now on, there is the `latest`-tag, which points to the latest commit on the default-branch and there will be one new tag per release and a tag that points to the latest release per major version.
