### ISSUE TITLE
Add support for wildcards in the map file

### ISSUE THREAD

**Issue by marc0l92** [codekie/openapi-examples-validator#170]
Hello, in order to reduce the work needed to add a new test in the map I would like to add the support for wildcards in the map file.

Example:
```json
{
  "$.paths./.get.responses.200.schema": [
    "test/basic/*",
    "test/advanced/*",
  ],
  "$.paths./.get.responses.300.schema": "test/*"
}
```

In this way any new test added in the correct folder will be automatically detected by the script without having to update the map

**Comment by codekie** [comment]
Sounds good 👍 . PRs are welcome
