### ISSUE TITLE
Support of schema combiner for --no-additional-proprierties

### ISSUE THREAD

**Issue by marc0l92** [codekie/openapi-examples-validator#174]
Hello,
I see in the Readme.md and in the code that you are skipping any model that contains one of the schema composition keywords.

Why are you doing this?
There were some impediments in supporting this feature? or it was just not your priority while creating the library?

**Comment by codekie** [comment]
It's been a while, but if I remember correctly, this was the reason:

https://stackoverflow.com/questions/22689900/json-schema-allof-with-additionalproperties#answer-23001194

**Comment by marc0l92** [comment]
In my company we use the `allOf` keywork a lot, and I would like to make the option `--no-additional-properties` works for those openapi files.

Would it be ok for you to implement an option like `--merge-allof-definitions`?
This option will be executed before the `--no-additional-proprierties` and it will merge the definitions that uses `allOf` in order to make the compatible with the additional properties check.

Example:
A definition like this:
```
{
  "allOf": [
    {
      "type": "object",
      "properties": {
        "prop1": {
          "type": "string"
        }
      }
    },
    {
      "type": "object",
      "properties": {
        "prop2": {
          "type": "string"
        }
      }
    }
  ]
}
```
with the option `--merge-allof-definitions` it will be converted to
```
{
  "type": "object",
  "properties": {
    "prop1": {
      "type": "string"
    }
    "prop2": {
      "type": "string"
    }
  }
}
```
In this way it will not be skipped by the `--no-additional-proprierties` option.

**Comment by codekie** [comment]
I'm ok with that 👍. Please also point out in the README.md, in the caveat section why this option exists.

**Comment by marc0l92** [comment]
I'm coding this feature and I would like to have your opinion on an issue I'm facing.
While merging two objects inside the allOf combiner, if one of them use the rule `minProperties` or `maxProperties`, should I drop this rule and print a warning or should I sum the amount of properties allowed?

What does it looks more correct to you?

**Comment by codekie** [comment]
@marc0l92 from my point of view, both properties (`minProperties` and `maxProperties`) should be applied. But now as I think of it, I see a more concerning issue.. How to deal with schemas with conflicting definitions or properties? For instance if one schema declares `minProperties: 3` and the other one `minProperties: 5`?

Or even worse (see `id` specifically):

```yaml
...
              schema:
                allOf:
                  - $ref: '#/components/schemas/Pet'
                  - $ref: '#/components/schemas/Doggo'
...

components:
  schemas:
    Pet:
      required:
        - id
      type: object
      properties:
        id:
          type: string
    Doggo:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        age:
          type: number
```

I think, there is no clean solution to resolve these kinds of "merge conflicts". So, from my point of view, if there are conflicting properties, the validation should not be executed and after the merge-attempt, the process should be aborted with a proper error message, pointing out the paths of the conflicting properties.

**Comment by codekie** [comment]
@marc0l92 But then, there also may be cases like one schema defines `minProperties: 5` and the other one defines `maxProperties:3`. These kind of issues also should be addressed. Considering this, I'm not sure if it's a good decision to implement all this logic in this tool, as the purpose of the OEV (OpenAPI Examples Validator) is to validate examples against their schema and it should focus on this specific purpose, rather then (internally) modifying the schema (and deal with the potential issues that may occur in this step).

Maybe it's wiser to let these (rather big) modifications on the schema be handled by a tool that has their focus on that (e.g. https://www.npmjs.com/package/json-schema-merge-allof) in a preceding step, independent of the OEV, then take the resulting schema and use it for validation.

What do you think?

**Comment by marc0l92** [comment]
You are right I did not thought about looking for a tool that does the merging specifically. We can delegate this job to that library.

I will update my pull request to remove the feature I was coding and just update the documentation in order to mention this library.

**Comment by codekie** [comment]
Thank you. I appreciate the efforts you already have put into this, though 👍

**Comment by marc0l92** [comment]
I really liked working with you.
Thanks for the great work with this library and for taking into account my requests.
