### ISSUE TITLE
discriminator does not support allOf

### ISSUE THREAD

**Issue by wcloete** [codekie/openapi-examples-validator#187]
Hi since https://github.com/codekie/openapi-examples-validator/pull/185 I have an API that is failing validation. It uses the `discriminator` keyword on the parent definition and `allOf` on the children.

## Example
This was adapted from [the OAS documentation for `discriminator`](https://swagger.io/specification/v3/#discriminator-object)

### API spec:
```yaml
openapi: 3.0.3
info:
  title: An API for a cat.
  version: 0.1.9
paths:
  /cat:
    get:
      responses:
        '200':
          description: It is just a cat.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cat'
              examples:
                ex1:
                  value:
                    petType: "Cat"
                    name: "misty"
components:
  schemas:
    Pet:
      type: object
      required:
      - petType
      properties:
        petType:
          type: string
      discriminator:
        propertyName: petType
    Cat:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Cat`
        properties:
          name:
            type: string
    Dog:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Dog`
        properties:
          bark:
            type: string
    Lizard:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Lizard`
        properties:
          lovesRocks:
            type: boolean
```

### Validate with:
```bash
openapi-examples-validator openapi.yaml
```

### Error:
```
Validating examples
Schemas with examples found: 1
Examples without schema found: 0
Total examples found: 1

Errors found.

[
    {
        "type": "Validation",
        "message": "discriminator: requires oneOf keyword",
        "examplePath": "/paths/~1cat/get/responses/200/content/application~1json/examples/ex1/value"
    }
]
```

## Other info
Version: openapi-examples-validator@5.0.0
Operating system: https://hub.docker.com/_/node, image ID acd15857ce39
OpenAPI version: 3.0.3

**Comment by codekie** [comment]
@wcloete Thank you for your report, but I use [Ajv](https://ajv.js.org/) under the hood for the validation and it only supports `oneOf` with the [discriminator](https://ajv.js.org/json-schema.html#discriminator) keyword (yet), so there's not much I can do about it at this point.

**Comment by codekie** [comment]
@wcloete I just had a closer look at your example again.. Your example is not how the discriminator is supposed to be used.

If you just want to inherit a schema, you don't need the `discriminator`. Drop the `discriminator` it in your example and it works.

**Comment by wcloete** [comment]
Strange, because as I say, I took the schemas almost verbatim from the [docs](https://swagger.io/specification/v3/#discriminator-object) - my only change was to remove `mapping` and add an endpoint.

The paragraph above the example even says
> In both the oneOf and anyOf use cases, all possible schemas MUST be listed explicitly. To avoid redundancy, the discriminator MAY be added to a parent schema definition, and all schemas comprising the parent schema in an allOf construct may be used as an alternate schema.

But as you say, Ajv only supports `oneOf` according to their documentation, so this one will keep failing until they add support.

Thank you for your time, and for a nice library!

**Comment by codekie** [comment]
I can't promise that this will resolve your issue, but `2261` really is a problem as that is a common use case.

**Comment by wcloete** [comment]
Yes, it looks like 2261 covers what I need. I'll keep an eye out for updates too.
