### ISSUE TITLE
Support YAML Format

### ISSUE THREAD

**Issue by geoffreywiseman** [codekie/openapi-examples-validator#19]
Seems like the validator doesn't support YAML; while certainly I can convert the YAML to JSON and then validate, would be nice if the validator would handle that for me. ;)

**Comment by geoffreywiseman** [comment]
Is this going up to NPM anytime? Is it waiting on other enhancements to get bundled?

**Comment by codekie** [comment]
I intended to bundle this feature with other ones, since this is a breaking change and will result in a bump in the major version, but since I won't have much time in the near future, I might as well release this version now.

**Comment by codekie** [comment]
Released
