### ISSUE TITLE
Unknown format int32?

### ISSUE THREAD

**Issue by geoffreywiseman** [codekie/openapi-examples-validator#42]
I haven't been able to make much use of this on a recent project because most of my examples are request examples, so I was excited to see request examples get fixed this morning, and I quickly tried a checkout and test so that I didn't have to wait for an NPM release, only to hit:

```
/path/to/openapi-examples-validator/node_modules/ajv/lib/ajv.js:351
    throw e;
    ^

Error: unknown format "int32" is used in schema at path "#/components/schemas/path/to/my/property"
    at Object.generate_format [as code] (/path/to/openapi-examples-validator/node_modules/ajv/lib/dotjs/format.js:69:15)
```

I was able to quickly confirm that `int32` is a format listed in OAS, and that there didn't seem to be anything immediately wrong with the API doc, at least, nothing that I found.

While this issue comes up in `ajv` code, I quickly scanned their repo, and I can see they support formats, but that there may be a plugin model and other complexities to consider, so I decided that I should report it on `openapi-examples-validator`, and if there's an underlying issue with `ajv`, you're more likely to have a better understanding of that than I am.

**Comment by codekie** [comment]
After having a closer look at this matter, I've found out that `ajv` doesn't natively support formats for numbers. It is possible to add custom format-validators, though. After a quick test, adding validators for the formats `int32`, `float` and `double` shouldn't be a big problem.

however, `int64` I can only offer as a format to `string` for now (due to the precision-limitation for Javascript-numbers).

**Comment by geoffreywiseman** [comment]
Yup, that helped for me -- looks like I'm not currently using any int64 anyway.

```
❯ node src/cli path/to/openapi.yml
Validating examples
Response schemas with examples found: 6
Response examples without schema found: 0
Total examples found: 6

No errors found.
```

**Comment by codekie** [comment]
I'm glad to hear that. Thanks for your reports, btw. I really appreciate them!
