### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by thim81** [codekie/openapi-examples-validator#78]
Hi @codekie 

I'm interested in running some validation, but I struggle with how to use it.

I'm looking in the tests, but I don't fully understand how the `openapi-examples-validator -s $.paths./.get.responses.200.schema  -e example.json openapi-spec.json` works?

Could you a  simple "example.json" and the "openapi-spec.json"?
That would help with understanding if the schema should be defined or not?

**Comment by thim81** [comment]
I think that you don't need to define any "e" or "s" parameters if the examples are in the spec.

**Comment by codekie** [comment]
Exactly. As stated in the readme:

> If an external example has to be verified, the `-s` and `-e` option has to be used.
> 
> For example:
> 
> ```
> $ openapi-examples-validator -s $.paths./.get.responses.200.schema -e example.json openapi-spec.json
> ```
> 

This means, if you have an example that is not included in the spec, you have to pass the example file and the JSON-Path to the corresponding OpenAPI-definition within the spec.

For example:

```sh
node dist/cli.js -s $.paths./.get.responses.200.schema -e test/data/v2/external-examples-valid-example1.json test/data/v2/external-examples-schema.json
```
